apiVersion: devtools.immich.app/v1alpha1
kind: Preview
metadata:
  labels:
    app.kubernetes.io/name: preview
    app.kubernetes.io/instance: preview-sample
    app.kubernetes.io/part-of: preview-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: preview-operator
  name: preview-sample
spec:
  immich:
    tag: main
