name: 'Terragrunt'
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - "tf/**"
      - ".github/workflows/terragrunt.yml"
      - ".mise/config.toml"
  push:
    branches: [ "main" ]
    paths:
      - "tf/**"
      - ".github/workflows/terragrunt.yml"
      - ".mise/config.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  working_dir: 'tf/deployment'
  TG_NON_INTERACTIVE: 'true'
permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@143a85f84a90555d121cde2ff5872e393a47ab9f # v1.0.0
        with:
          version: 2.30.3

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@697a75e2c3186d3c037c2c159855cf2d566542ba # use-mise-action-0.0.1

      - name: Check Formatting
        run: terragrunt hcl format --check --diff

      - name: Check terraform fmt
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_TF_DEV_ENV }}
          ENVIRONMENT: dev
        run: mise run tf fmt -- -diff -check
  plan:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    permissions:
      contents: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@143a85f84a90555d121cde2ff5872e393a47ab9f # v1.0.0
        with:
          version: 2.30.3

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@697a75e2c3186d3c037c2c159855cf2d566542ba # use-mise-action-0.0.1

      - name: Plan Shared
        working-directory: ${{ env.working_dir }}/modules/shared
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_TF_PROD_ENV }}
          ENVIRONMENT: prod
        run: mise run tf:plan

      - name: Plan Dev
        working-directory: ${{ env.working_dir }}/modules/scoped
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_TF_DEV_ENV }}
          ENVIRONMENT: dev
        run: mise run tf:plan

      - name: Plan Prod
        working-directory: ${{ env.working_dir }}/modules/scoped
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_TF_PROD_ENV }}
          ENVIRONMENT: prod
        run: |
          mise run tf:init
          mise run tf:plan

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@143a85f84a90555d121cde2ff5872e393a47ab9f # v1.0.0
        with:
          version: 2.30.3

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@697a75e2c3186d3c037c2c159855cf2d566542ba # use-mise-action-0.0.1

      - name: Deploy Shared
        working-directory: ${{ env.working_dir }}/modules/shared
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_TF_PROD_ENV }}
          ENVIRONMENT: prod
        run: mise run tf:apply

      - name: Deploy Dev
        working-directory: ${{ env.working_dir }}/modules/scoped
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_TF_DEV_ENV }}
          ENVIRONMENT: dev
        run: mise run tf:apply

      - name: Deploy Prod
        working-directory: ${{ env.working_dir }}/modules/scoped
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_TF_PROD_ENV }}
          ENVIRONMENT: prod
        run: |
          mise run tf:init
          mise run tf:apply
